#!/bin/bash
## See: https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update

sudo apt-get install oracle-java8-installer

## Optionally install Java 9
#sudo apt-get install oracle-java9-installer

## Then managing Java using
sudo update-alternatives --config java
